### ISSUE TITLE
Windows 下 PAC 的 JS 引擎不支持 reduce 函数

### ISSUE THREAD

**Issue by humiaozuzu** [blackgear/mono_pac#11]
如题所示，因为使用了 reduce 函数会出现这个问题，IE 和 Dropbox 等第三方应用都无法使用代理了。

不知道可以提供一下解决方法吗？

**Comment by blackgear** [comment]
It should be fixed now.

**Comment by humiaozuzu** [comment]
恩，经过测试确实生效了
