### ISSUE TITLE
dnsResolve()方法并不能解析到IPV6地址？

### ISSUE THREAD

**Issue by autulin** [blackgear/mono_pac#13]
本机已经更换了IPV6的hosts，在正常情况下直连访问google、youtube都没有问题的。

按照本项目的思路，用dnsResolve()方法解析到IPV6地址应该是可以直接连接的

但是我发现此方法并不能正确解析到IPV6的地址，准确的说解析到的值为“null”。

比如，可以在PAC中输出一下解析的结果，然后看到的结果如下：
```JavaScript
    ...
    var o = dnsResolve(a); //DNS解析
    alert(a+":"+o);
    ...
```
![null](https://cloud.githubusercontent.com/assets/16400368/21073400/e741692c-bf17-11e6-8087-5fbc76c3934e.PNG)

**Comment by blackgear** [comment]
> dnsResolve return IPv4 only in IE and Chromium, dnsResolve can return IPv6 in Firefox.
> 
> IE via http://blogs.msdn.com/b/wndp/archive/2006/07/18/ipv6-wpad-for-winhttp-and-wininet.aspx
> 
> Chromium via https://code.google.com/p/chromium/issues/detail?id=24641
> 
> Firefox via https://github.com/blackgear/mono_pac/pull/2
> 
via https://github.com/blackgear/mono_pac#details

`dnsResolveEx` may helps you. (Windows Vsita and newer only, ref: IE's link)
