### ISSUE TITLE
It crashes my OneNote and its Crash Reporter

### ISSUE THREAD

**Issue by lucifer662607004** [blackgear/mono_pac#3]
My make command: 
python ./make.py -p "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080" -o ./proxy.pac 

am I doing this correctly?

when I use SOCKS agent directly everything goes well, but as long as I switch to PAC some application crashes such as OneNote. what's more when I click "send report" after a crash the crash reporter crashes too....sad.

**Comment by blackgear** [comment]
PAC does NOT work for all protocol. Someone has said that OneNote does not take concern of PAC via https://www.v2ex.com/t/180780 L9.

You may try this PAC first:

```
function FindProxyForURL(url, host) {
    return "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080";
}
```

To see if OneNote use PAC.

**Comment by lucifer662607004** [comment]
hahahahaha!!! 
I'm the L9 in https://www.v2ex.com/t/180780 !!! 
My ID is wohenyingyu01 in v2ex!!! 
I guess I'm the only one who uses PAC with OneNote in the world !!!  
sad!!!
When I post it I meant OneNote couldn't sync to OneDrive(which is blocked), I didn't mean it crashed. 

OK, here is the test result: there is absolutely no problem with this PAC file:
'''
function FindProxyForURL(url, host) {
return "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080";
}
'''
OneNote works like a charm. 

Actually I have tested so many PAC files but only your file crashes OneNote. I don't know what happens, where can I find the log or something like that???

Thank you for replying.

**Comment by blackgear** [comment]
I guess maybe the `dnsResolve` or `isPlainHostName` will be the fault.

You can try to add `return "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080";` in center of the PAC files and see if skip codes after `var IP = dnsResolve(host);` make sense.
