### ISSUE TITLE
为什么生成的文件ie11不能用呢

### ISSUE THREAD

**Issue by outmanout** [blackgear/mono_pac#7]
如题
ie11不支持本地pac文件，已通过ss加载到ie11中还是无法使用，还需要什么特别的设置吗？

**Comment by blackgear** [comment]
请给出更多信息，如生成时使用的参数，所谓不能用的具体表现等等…

**Comment by outmanout** [comment]
先谢谢您的帮助！为作者的默默贡献点赞！
我生成时使用的参数是：make.py -p "SOCKS5 127.0.0.1:1080;SOCKS 127.0.0.1:1080" -o ./proxy.pac
生成的proxy.pac文件，在chrome中用swithyomega插件加载没有问题。但是将生成的文件做为“SS-->系统代理-->pac模式”的配置文件后，发现我的IE并没有按期望工作，比如打开github有如下提示：
![unnamed qq screenshot20151015103457](https://cloud.githubusercontent.com/assets/10810823/10503553/c1f0aa38-7329-11e5-9216-740b5b50bc7f.png)
而同样用此文件，chrome打开则完全没有问题。电脑小白，不知道说清楚没有。

**Comment by xream** [comment]
@outmanout 我记得 IE 不支持 SOCKS5 代理 换 HTTP 代理试试吧

**Comment by blackgear** [comment]
IE 确实不支持 SOCKS 系列的代理，你看看你的 ss 有没有提供 HTTP 代理的选项吧……
